I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 16, in script call
    call day1_gunshop
  File "game/scripts/script.rpy", line 201, in script
    karoi "It's alright, we're actually going to go across the street and get some ice cream."
Exception: Sayer 'karoi' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 16, in script call
    call day1_gunshop
  File "game/scripts/script.rpy", line 201, in script
    karoi "It's alright, we're actually going to go across the street and get some ice cream."
  File "E:\Work\VisualNovel\renpy-6.18.3-sdk\renpy\ast.py", line 573, in execute
    who = eval_who(self.who, self.who_fast)
  File "E:\Work\VisualNovel\renpy-6.18.3-sdk\renpy\ast.py", line 491, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'karoi' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.1.329
GreenT 0.0
